### ISSUE TITLE
Cannot find module 'babel-preset-env' from '/node_modules/@babel/preset-env/node_modules/caniuse-lite'

### ISSUE THREAD

**Issue by dinesh2609** [ben-eb/caniuse-lite#13]
I am trying to build my project via "node:8.9.2-alpine" docker image.

> > web@0.0.0 build /
> > babel-node tools/run build "--release" "--verbose"
> 
> 
> /node_modules/@babel/core/lib/config/option-manager.js:120
>       throw e;
>       ^
> 
> 
> Error: [BABEL] /node_modules/@babel/preset-env/node_modules/caniuse-lite/dist/unpacker/agents.js: Cannot find module 'babel-preset-env' from '/node_modules/@babel/preset-env/node_modules/caniuse-lite'
> - Did you mean "@babel/env"?
>     at Function.module.exports [as sync] (/node_modules/resolve/lib/sync.js:40:15)
>     at resolveStandardizedName (/node_modules/@babel/core/lib/config/loading/files/plugins.js:78:29)
>     at resolvePreset (/node_modules/@babel/core/lib/config/loading/files/plugins.js:31:10)
>     at loadPreset (/node_modules/@babel/core/lib/config/loading/files/plugins.js:50:18)
>     at createDescriptor (/node_modules/@babel/core/lib/config/option-manager.js:443:21)
>     at /node_modules/@babel/core/lib/config/option-manager.js:173:12
>     at Array.map (<anonymous>)
>     at /node_modules/@babel/core/lib/config/option-manager.js:172:48
>     at cachedFunction (/node_modules/@babel/core/lib/config/caching.js:40:17)
>     at /node_modules/@babel/core/lib/config/option-manager.js:90:14

package.json file 

```
  "dependencies": {
    "@babel/polyfill": "7.0.0-beta.34",
   ...
}
```
```

"devDependencies": {
    "@babel/core": "7.0.0-beta.34",
    "@babel/node": "7.0.0-beta.34",
    "@babel/plugin-transform-react-constant-elements": "7.0.0-beta.34",
    "@babel/plugin-transform-react-inline-elements": "7.0.0-beta.34",
    "@babel/plugin-transform-react-jsx-self": "7.0.0-beta.34",
    "@babel/plugin-transform-react-jsx-source": "7.0.0-beta.34",
    "@babel/preset-env": "7.0.0-beta.34",
    "@babel/preset-flow": "7.0.0-beta.34",
    "@babel/preset-react": "7.0.0-beta.34",
    "@babel/preset-stage-2": "7.0.0-beta.34",
    .....
}

```
.babelrc.js
```

module.exports = {
  presets: [
    [
      '@babel/preset-env',
      {
        targets: {
          node: 'current',
        },
      },
    ],
    '@babel/preset-stage-2',
    '@babel/preset-flow',
    '@babel/preset-react',
  ],
  ignore: ['node_modules', 'build'],
};

```

**Comment by GrosSacASac** [comment]
Hi, I got the (almost the) same error for a completely different package. What the errors have in common is the fact that webpack and babel and some babel plugins, can you reopen the issue in github webpack ? I think it comes from there

**Comment by ben-eb** [comment]
Hi,

Not really sure to be honest. It seems like the script is trying to pick up the Babel configuration from this package, I don't know why because it is transpiled before it is published to npm. I don't think it's an issue with caniuse-lite though.
