### ISSUE TITLE
Changing the license?

### ISSUE THREAD

**Issue by JackuB** [ben-eb/caniuse-lite#14]
[Creative commons advise against using CC license for software.](https://creativecommons.org/faq/#can-i-apply-a-creative-commons-license-to-software) Would you be open to changing it? Could create a PR with a change to MIT.

**Comment by ben-eb** [comment]
@JackuB The generated output from this project is wholly derived from caniuse, so I thought it would be best to keep the original license. The data is not for me to relicense as my own so please contact Alexis instead regarding licensing. Thanks!

https://github.com/Fyrd/caniuse#readme
