### ISSUE TITLE
Wrong `css-placeholder`

### ISSUE THREAD

**Issue by aleen42** [ben-eb/caniuse-lite#16]
Since `data/features/css-placeholder.js` was modified last day, `autoprefixer` has changed its behaviour when adding prefixer for placeholder styles, as the file stated that `ie 10` and `ie 11` were not in the compatibility list.

Correct browser list should be show as followed:

> and_qq 1.2,android 2.1,android 2.2,android 2.3,android 3,android 4,android 4.1,android 4.4,android 4.4.3-4.4.4,android 60,bb 7,bb 10,chrome 4,chrome 5,chrome 6,chrome 7,chrome 8,chrome 9,chrome 10,chrome 11,chrome 12,chrome 12.1,chrome 13,chrome 14,chrome 15,chrome 16,chrome 17,chrome 18,chrome 19,chrome 20,chrome 21,chrome 22,chrome 23,chrome 24,chrome 25,chrome 26,chrome 27,chrome 28,chrome 29,chrome 30,chrome 31,chrome 33,chrome 34,chrome 35,chrome 36,chrome 37,chrome 38,chrome 39,chrome 40,chrome 41,chrome 42,chrome 43,chrome 44,chrome 45,chrome 46,chrome 47,chrome 48,chrome 49,chrome 50,chrome 51,chrome 52,chrome 53,chrome 54,chrome 55,chrome 56,edge 12,edge 13,edge 14,edge 15,edge 16,edge 17,edge 18,firefox 4,firefox 5,firefox 6,firefox 7,firefox 8,firefox 9,firefox 10,firefox 11,firefox 12,firefox 12.1,firefox 13,firefox 14,firefox 15,firefox 16,firefox 17,firefox 18,firefox 19,firefox 20,firefox 21,firefox 22,firefox 23,firefox 24,firefox 25,firefox 26,firefox 27,firefox 28,firefox 29,firefox 30,firefox 31,firefox 33,firefox 34,firefox 35,firefox 36,firefox 37,firefox 38,firefox 39,firefox 40,firefox 41,firefox 42,firefox 43,firefox 44,firefox 45,firefox 46,firefox 47,firefox 48,firefox 49,firefox 50,ie 10,ie 11,ie_mob 10,ie_mob 11,ios_saf 5.0-5.1,ios_saf 6.0-6.1,ios_saf 7.0-7.1,ios_saf 8,ios_saf 8.1-8.4,ios_saf 9.0-9.2,ios_saf 9.3,ios_saf 10.0-10.2,ios_saf 60,opera 12.1,opera 15,opera 16,opera 17,opera 18,opera 19,opera 20,opera 21,opera 22,opera 23,opera 24,opera 25,opera 26,opera 27,opera 28,opera 29,opera 30,opera 31,opera 33,opera 34,opera 35,opera 36,opera 37,opera 38,opera 39,opera 40,opera 41,opera 42,opera 43,safari 5,safari 5.1,safari 6,safari 6.1,safari 7,safari 7.1,safari 8,safari 9,safari 9.1,safari 10,samsung 4,samsung 5,samsung 6.2

But I got the wrong one last day:

> browsers: and_qq 1.2,android 2.1,android 2.2,android 2.3,android 3,android 4,android 4.1,android 4.2-4.3,android 4.4.3-4.4.4,android 4.4,bb 7,bb 10,chrome 4,chrome 5,chrome 6,chrome 7,chrome 8,chrome 9,chrome 10,chrome 11,chrome 12,chrome 13,chrome 14,chrome 15,chrome 16,chrome 17,chrome 18,chrome 19,chrome 20,chrome 21,chrome 22,chrome 23,chrome 24,chrome 25,chrome 26,chrome 27,chrome 28,chrome 29,chrome 30,chrome 31,chrome 32,chrome 33,chrome 34,chrome 35,chrome 36,chrome 37,chrome 38,chrome 39,chrome 40,chrome 41,chrome 42,chrome 43,chrome 44,chrome 45,chrome 46,chrome 47,chrome 48,chrome 49,chrome 50,chrome 51,chrome 52,chrome 53,chrome 54,chrome 55,chrome 56,edge 12,edge 13,edge 14,edge 15,edge 16,edge 17,edge 18,firefox 19,firefox 20,firefox 21,firefox 22,firefox 23,firefox 24,firefox 25,firefox 26,firefox 27,firefox 28,firefox 29,firefox 30,firefox 31,firefox 32,firefox 33,firefox 34,firefox 35,firefox 36,firefox 37,firefox 38,firefox 39,firefox 40,firefox 41,firefox 42,firefox 43,firefox 44,firefox 45,firefox 46,firefox 47,firefox 48,firefox 49,firefox 50,ie_mob 10,ie_mob 11,ios_saf 4.2-4.3,ios_saf 5.0-5.1,ios_saf 6.0-6.1,ios_saf 7.0-7.1,ios_saf 8,ios_saf 8.1-8.4,ios_saf 9.0-9.2,ios_saf 9.3,ios_saf 10.0-10.2,opera 15,opera 16,opera 17,opera 18,opera 19,opera 20,opera 21,opera 22,opera 23,opera 24,opera 25,opera 26,opera 27,opera 28,opera 29,opera 30,opera 31,opera 32,opera 33,opera 34,opera 35,opera 36,opera 37,opera 38,opera 39,opera 40,opera 41,opera 42,opera 43,safari 5,safari 5.1,safari 6,safari 6.1,safari 7,safari 7.1,safari 8,safari 9,safari 9.1,safari 10,samsung 4,samsung 5,samsung 6.2

It resulted in a wrong prefixer generated:

```css
.input::-webkit-input-placeholder {
    color: black;
}

.input::-ms-input-placeholder {
    color: black;
}

.input::placeholder {
    color: black;
}
```

Apparently, it has missed the following style for IE10 and IE11:

```css
.input:-ms-input-placeholder {
    color: black;
}
```

**Comment by aniude** [comment]
https://github.com/Fyrd/caniuse/issues/4095

**Comment by ai** [comment]
I am closing it, since it is `caniuse-db`
