### ISSUE TITLE
caniuse-lite@^1.0.30000884 Unexpected end of JSON input while parsing near '...^0.7.1","split":"^1.0'

### ISSUE THREAD

**Issue by Eusen** [ben-eb/caniuse-lite#17]
`npm ERR! Unexpected end of JSON input while parsing near '...^0.7.1","split":"^1.0'`

hi guys, Are you serious? NPM can not download!

**Comment by Eusen** [comment]
Now ionic angular is unable to create new projects! Good job =-=

**Comment by andyjansson** [comment]
I understand that you're frustrated, but I think you could affort being a bit nicer. The latest version is 1.0.30000906. Have you tried updating your dependencies? If that doesn't work, have you tried targeting an older version?

**Comment by Eusen** [comment]
ok, alright, I will close it, but please don't make such a low grade mistake again.

**Comment by Eusen** [comment]
![image](https://user-images.githubusercontent.com/14822175/48128285-f1047700-e2c0-11e8-9911-1080a661216c.png)
see, all the libraries are up to date. Neither angular nor ionic can be installed.
