### ISSUE TITLE
Is this version released 1.0.30000929?

### ISSUE THREAD

**Issue by pushpa446** [ben-eb/caniuse-lite#19]
When I try to install 1.0.30000929 version using, 
npm install caniuse-lite@^1.0.30000929
It is successfully installed. But I am not able to see this version in the releases page and not in package.json version property.

Can someone help?
Maybe it's a dumb question.

**Comment by erbzn** [comment]
+1

**Comment by ai** [comment]
I am closing it since it is not relevant anymore
