### ISSUE TITLE
404 caniuse-lite-1.0.30000938.tgz

### ISSUE THREAD

**Issue by robotnic** [ben-eb/caniuse-lite#20]
hi all

I try to install caniuse-lite:

```
npm i caniuse-lite
```
But I get a 404 Not Found 
npm ERR! 404 Not Found: caniuse-lite@ ... caniuse-lite-1.0.30000938.tgz

Looks like something went wrong with 938 release. 

![image](https://user-images.githubusercontent.com/219020/52852281-6f6e8180-3118-11e9-805e-22933fbfe9f9.png)

**Comment by ai** [comment]
It is `npm` problem
