### ISSUE TITLE
Add Safari iOS 12.2 support

### ISSUE THREAD

**Issue by avrelaun** [ben-eb/caniuse-lite#23]
Hi, we are relying on [browserslist-useragent](https://github.com/browserslist/browserslist-useragent) to display a warning in our webapp asking users to upgrade old browsers.

This package depends on caniuse-lite, and it seems we have a problem with safari 12.2 on iOS, it does not match the query described on the issue here: https://github.com/browserslist/browserslist-useragent/issues/40

I installed the latest caniuse-lite package (1.0.30000957) to make sure it was not already fixed, and it's not. Am i correct thinking this is a caniuse-lite db issue ?

**Comment by ai** [comment]
You should send PR to `caniuse-db` since `caniuse-lite` is just repackaging
