### ISSUE TITLE
npm package outdated

### ISSUE THREAD

**Issue by dasa** [ben-eb/caniuse-lite#29]
The last version published to npm is 1.0.30000989: https://www.npmjs.com/package/caniuse-lite

**Comment by dasa** [comment]
Ping please 🙏

**Comment by ai** [comment]
I will investigate why auto-release was stopped at Monday

**Comment by ai** [comment]
I fixed repackaging script. Hope it will work well on next `caniuse-db` release.

**Comment by dasa** [comment]
1.0.30000997 is now published!

**Comment by dasa** [comment]
Hi, publishing is broken again. The latest published version is: 1.0.30001066

**Comment by ai** [comment]
Oh, fuck. I started [funding](https://opencollective.com/browserslist) to refactor `caniuse-lite` build process to avoid cases like this. But nobody helped me in funding :(.
