### ISSUE TITLE
Add tests and CI coverage

### ISSUE THREAD

**Issue by amilajack** [ben-eb/caniuse-lite#3]
There's been some discussion regarding adding `caniuse-lite` as a dependency of `eslint-plugin-compat`. I'm somewhat reluctant to add tests if this module doesn't have any tests. What are thoughts on adding some tests to this project?

**Comment by ben-eb** [comment]
I'm not sure what missing tests you're referring to, we have four test files here: https://github.com/ben-eb/caniuse-lite/tree/master/src

**Comment by amilajack** [comment]
My bad. I didn't expect the test to be in the `src` dir.
