### ISSUE TITLE
Missing release binary for 1.0.30000999 in github

### ISSUE THREAD

**Issue by aermicioi** [ben-eb/caniuse-lite#30]
Hi, the latest release on npmjs is 1.0.30000999 while binary for it is missing in here on github. This is causing exact issues as in issue #26 while generating typescript angular client. npm while installing dependencies fails to find latest release version. Please publish compiled binaries for latest version.

**Comment by ai** [comment]
Here is a commit for 1.0.30000999 https://github.com/ben-eb/caniuse-lite/commit/597a8cba036c21425328bf699ec5be1be286dfa6

Is it what are you looking for?

**Comment by aermicioi** [comment]
Never mind, issue solved itself magically.
