### ISSUE TITLE
No matching version found for caniuse-lite@^1.0.30001004

### ISSUE THREAD

**Issue by Lincyy** [ben-eb/caniuse-lite#32]
Hi,
I'm getting the following error on my CI server
npm ERR! code ETARGET
npm ERR! notarget No matching version found for caniuse-lite@^1.0.30001004
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

**Comment by ai** [comment]
It is a temporary npm issue (maybe a problem with mirroring). npm registry has this version https://www.npmjs.com/package/caniuse-lite

**Comment by Lincyy** [comment]
Hey Andrey,
I yet see the version in package.json to be 1.0.30001002?

**Comment by ai** [comment]
Seems like it is npm CDN problem.

I see 1.0.30001004 in Japan.

**Comment by Lincyy** [comment]
Any idea Andrey how much time it takes for all CDNs to take up the
latest version? 'Coz we are stuck in production.

Thanks,
Lincy

**Comment by ai** [comment]
Sorry, I have no idea since it is npm error. Try to create issue on npm website

**Comment by Lincyy** [comment]
Thanks, I'll do that!

**Comment by Lincyy** [comment]
Hey Andrey,
Do you mind sending me the commit for the version upgrade. I could just add
that to my issue with npm.

Thanks,
Lincy

**Comment by ai** [comment]
Sure https://github.com/ben-eb/caniuse-lite/commit/4b208f293dc5fc5a3f5b646db9405a03fd6d0853#diff-b9cfc7f2cdf78a7f4b91a753d10865a2L39

**Comment by Lincyy** [comment]
Hey Andrey,

Could you please verify the package.json version for the commit you
mentioned? It is yet  "version": "1.0.30001002" in
https://github.com/ben-eb/caniuse-lite/blob/master/package.json

Thanks,
Lincy

**Comment by ai** [comment]
Hm. Let's me double check.

**Comment by ai** [comment]
But not, that it is not relevant to your issue since I can install `1.0.3000104` without problems in Japan.

**Comment by ai** [comment]
Here is right commit (server made it yesterday but didn’t push to github)
https://github.com/ben-eb/caniuse-lite/commit/1822f2f50d89912e1c9524322effdfcad5c11a11
