### ISSUE TITLE
Data packed with wrong version of caniuse-db

### ISSUE THREAD

**Issue by Beretta1979** [ben-eb/caniuse-lite#42]
It seems that the generated files in the ./data folder that are published to npm are generated with the wrong version of caniuse-db. If I manually run the `npm run pack` script the generated files do match the correct version of caniuse-db. 

I included a zip with the different ./data/agents.js file as an example:
- one file is the current file on master (version 1.0.30001023 / commit ab8f1ec1681d614ed7696437d70762557b526dcb)
- one file is packed with caniuse-db 1.0.30001021
- one file is packed with caniuse-db 1.0.30001023
[agents.zip](https://github.com/ben-eb/caniuse-lite/files/4124848/agents.zip)

As you can see the file for version 1.0.30001023 matches caniuse-db 1.0.30001021 instead. Probably there is a problem with your automated builds.

I noticed this because browserslist does not return edge version 79 in it's query results for this version :)

**Comment by ai** [comment]
Yeap seems like it is a problem with builds. 

Unfortunately, it requires big build scripts refactoring (including fixing few security issues). As a quick fix, we can wait for the next `caniuse-db` update, which will push new changes.

But I agree that we need refactoring. We are collecting donation to finish [this refactoring](https://github.com/browserslist/browserslist/issues/432):
https://opencollective.com/browserslist

Feel free to talk with your manager about supporting open source if this bug is critical for you.

**Comment by Beretta1979** [comment]
I created a PR that should fix this issue.

**Comment by ai** [comment]
@Beretta1979 because of how `caniuse-lite` auto-publish run it could take few days for me to update the script on the server.

**Comment by Beretta1979** [comment]
Hi ai, it seems that the auto start is not running, as caniuse-db has been updated and caniuse-lite does not seem to auto update. If I can help with anything please ask me.

**Comment by ai** [comment]
Seems like recentl changes killed auto-update 😔

I will try to connect to auto-release server to find a reason. But it could take few days.

**Comment by ai** [comment]
![20200203100356](https://user-images.githubusercontent.com/19343/73678107-7fa2a800-466c-11ea-8868-532b4c47c034.png)

Here is a log. Right now I have no idea what happened. We didn’t change anything related to Babel.

The current auto-release system is too unstable :(

**Comment by ai** [comment]
Just `npx babel-node` just work. Seems like `spawn` doesn’t see env variables.

Do you have any idea?

**Comment by Beretta1979** [comment]
It is locally reproducible at my side, trying to fix it now

**Comment by Beretta1979** [comment]
ai, I opened a PR which resolves the issue. Starting the babel-node command using npx seems to fix it.

**Comment by ai** [comment]
Thanks. Now it works.
