### ISSUE TITLE
WebRTC features

### ISSUE THREAD

**Issue by piranna** [ben-eb/caniuse-lite#47]
I can't not be able to find in the `data` files info about [WebRTC features](https://caniuse.com/#search=webrtc), both [rtcpeeconnecion](https://caniuse.com/#feat=rtcpeerconnection) or [objectrtc](https://caniuse.com/#feat=objectrtc). Shouldn't them be added?

**Comment by ai** [comment]
They should be in the package. Have no idea why it is available

**Comment by piranna** [comment]
In `master` branch, I can't not be able to find them both in the `data` folder nor searching in Github search bar... Maybe there's a bug why they are not included?

**Comment by ai** [comment]
Yeap. Can you investigate?

I do not have time for non-critical issues right now, but I will help you with PR, if you will find the source of the problem.

**Comment by poppinlp** [comment]
Is this been fixed? Since I can find it in the `data` folder right now.
![image](https://user-images.githubusercontent.com/1970625/85513822-f9dcc480-b62d-11ea-8edf-376bace0f0c2.png)

**Comment by piranna** [comment]
RTCPeerConnection [is added too](https://github.com/ben-eb/caniuse-lite/blob/master/data/features/rtcpeerconnection.js), seems it got fixed.
