### ISSUE TITLE
require(...).feature is not a function

### ISSUE THREAD

**Issue by ksorathiya** [ben-eb/caniuse-lite#50]
I started getting this error just today while running "npm run build" in my react app. 

 > react-scripts build
 /home/pi/builds/nxsWiCCc/0/XYZ/node_modules/autoprefixer/lib/supports.js:15
 var data = require('caniuse-lite').feature(require('caniuse-lite/data/features/css-featurequeries.js'));
                                    ^
 TypeError: require(...).feature is not a function

**Comment by ai** [comment]
Show `npm ls | grep caniuse-lite`

**Comment by ksorathiya** [comment]
I purged the node_modules folder and did "npm i" again and it solved the issue. It's working now but I wonder what could have gone wrong.

Thanks for responding.
