### ISSUE TITLE
Updating to 1.0.30001185 breaks application

### ISSUE THREAD

**Issue by kb-coder** [ben-eb/caniuse-lite#60]
I was trying to get an updated version of this package and after running the following command, I can no longer build the application:

npm update --depth 10 caniuse-lite

**Comment by ai** [comment]
> npm update --depth 10 caniuse-lite

This is now the recommended way to update `caniuse-lite`.

Try `npx browserslist@latest --update-db`

> I can no longer build the application:

What exactly error do you have after this command?

**Comment by kb-coder** [comment]
![image](https://user-images.githubusercontent.com/11179251/107714292-3f680380-6c8a-11eb-9998-3a0302ca73b8.png)

I think this may be an issue with Vue CLI. The highest version I can go up to is 1.0.30001164. If I go higher than that version, then I start getting errors about postcss loaders etc. I'll dig into this more tomorrow and raise an issue with Vue CLI.

![image](https://user-images.githubusercontent.com/11179251/107714120-ee580f80-6c89-11eb-9f33-a2faac54b553.png)



![image](https://user-images.githubusercontent.com/11179251/107714081-d97b7c00-6c89-11eb-80fe-24ccfbe5bcde.png)

**Comment by ai** [comment]
Very likely that this error came because you command updated all dependencies inside, not just `caniuse-lite`. Check the `package-lock.json` changes.

**Comment by kb-coder** [comment]
I confirmed that the issue is **not** caniuse-lite. I believe the issue is with a change in browserslist and how it processes queries.
