### ISSUE TITLE
javascript nullish coalescing and/or optional chaining

### ISSUE THREAD

**Issue by mreinstein** [ben-eb/caniuse-lite#63]
It would be great to be able to query by either/both of these:

https://caniuse.com/mdn-javascript_operators_optional_chaining

https://caniuse.com/mdn-javascript_operators_nullish_coalescing

**Comment by ai** [comment]
This project is just a repack of `caniuse-db`. You should open this issue in `caniuse-db`.

**Comment by mreinstein** [comment]
Thanks Andrey, sorry for the issue noise.
