### ISSUE TITLE
🚨 Project sustainability

### ISSUE THREAD

**Issue by ben-eb** [ben-eb/caniuse-lite#7]
This project needs a $5 commitment per month to run automatically. I am no longer willing to spend any more money on the server that is taking care of this and will be terminating it, and all further work on this project, on the 24th of July 2017, unless the $5 per month goal is met.

If it is important to you to have faster caniuse data downloads from npm & smaller client side builds, then please consider supporting this project financially. Thank you.

Patreon: https://www.patreon.com/beneb
Paypal: https://www.paypal.me/benebinfo

**Comment by ai** [comment]
I will talk to Evil Martians. I think we should have free resources for one docker container.

Also it may interest security a little since our DevOps developers are great.

**Comment by bfred-it** [comment]
Where is the server hosted? How often does `publish.js` run? Is this something that can be moved to now or lambda?

**Comment by ben-eb** [comment]
Right now it's running on a dedicated server that I'm not using for anything else, so I'm wanting to shut it down and move to DigitalOcean or similar virtual environment. `publish.js` runs every hour right now; haven't checked out now or lambda so I don't know; basically we need a user authorised for git & npm and a server with node/cron.

**Comment by bfred-it** [comment]
If this runs on lambda that's your best bet for this kind of activity (rare executions) since it also supports its own version of cron. 5x24x30 per months are gonna cost you $0 thanks to the unlimited free tier. The only "cost" is moving it there.

**Comment by ai** [comment]
https://aws.amazon.com/lambda/details/

**Comment by ben-eb** [comment]
I've decided to go with the base tier from Digital Ocean; we looked into Lambda but as the setup requires installing caniuse-db & having publish access to npm, it wasn't a good fit.

The main thing is that we're funded for the time being, thanks to Patreon. 🍻
